### ISSUE TITLE
captcha is not working

### ISSUE THREAD

**Issue by saiaashraya** [UCDS/health4all_v3#133]
Hi,

captcha is not working while login to admin/user portal. please check the attachment.

Thanks
![image](https://user-images.githubusercontent.com/97846202/149670641-5dbf71c1-06eb-4158-826f-91720cce1137.png)

**Comment by manojkumarmanusai** [comment]
Hi saiaashraya,

Please make sure that root directory has write permssion for all the users.

You can use the following command, if you are using Linux environment

chmod 555 -R <root_dir>

**Comment by saiaashraya** [comment]
Hi manoj,

I have tried using above command but, still same problem having it there is no captcha.

**Comment by manojkumarmanusai** [comment]
Hi saiaashraya,

Could you try runnning that command on htdocs/www direcotry.

ie. chmod 555 -R <root_dir>

if that not works, run

chmod 777 -R <root_dir>

**Comment by saiaashraya** [comment]
yes it is working

**Comment by manojkumarmanusai** [comment]
Great!
